import { ISideMenu } from '../types/globalTypes'
import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined'
import ShoppingCartOutlinedIcon from '@mui/icons-material/ShoppingCartOutlined'
import FormatListBulletedOutlinedIcon from '@mui/icons-material/FormatListBulletedOutlined'
import PersonOutlineOutlinedIcon from '@mui/icons-material/PersonOutlineOutlined'
import CircleOutlinedIcon from '@mui/icons-material/CircleOutlined'
import LocalShippingOutlinedIcon from '@mui/icons-material/LocalShippingOutlined'
import AttachMoneyOutlinedIcon from '@mui/icons-material/AttachMoneyOutlined'
import BrushOutlinedIcon from '@mui/icons-material/BrushOutlined'
import CreditCardOutlinedIcon from '@mui/icons-material/CreditCardOutlined'
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined'
import HelpOutlineRoundedIcon from '@mui/icons-material/HelpOutlineRounded'
import ShareRoundedIcon from '@mui/icons-material/ShareRounded'
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined'
import LanguageRoundedIcon from '@mui/icons-material/LanguageRounded'
import AppsRoundedIcon from '@mui/icons-material/AppsRounded'
import LogoutRoundedIcon from '@mui/icons-material/LogoutRounded'

export const SIDEBAR_MENUS: ISideMenu[] = [
    {
        id: '1',
        title: 'Dashboard',
        children: [],
        hasChildren: false,
        icon: HomeOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        hasSeparator: false,
        route: '/',
    },
    {
        id: '2',
        title: 'Catalouge',
        children: [],
        hasChildren: false,
        icon: ShoppingCartOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        hasSeparator: false,
        route: '/catalog',
    },
    {
        id: '3',
        title: 'Orders',
        children: [],
        hasChildren: false,
        icon: FormatListBulletedOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 14,
        hasSeparator: false,
        route: '/orders',
    },
    {
        id: '4',
        title: 'Customers',
        children: [],
        hasChildren: false,
        icon: PersonOutlineOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        hasSeparator: false,
        route: '/customers',
    },
    {
        id: '5',
        title: 'Marketing',
        children: [
            {
                id: '51',
                title: 'Discount codes',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                route: '/customers/test1',
                children: [],
            },
            {
                id: '52',
                title: 'Exit intent',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '53',
                title: 'Checkout Features',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '54',
                title: 'Post-purchase conversion',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '55',
                title: 'Timer checkout',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '56',
                title: 'Sell on Social',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '57',
                title: 'Special Offer',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
            {
                id: '58',
                title: 'Seasonal Offer',
                hasChildren: false,
                icon: '',
                isExpanded: false,
                isSelected: false,
                badgeValue: 0,
                children: [],
                route: '/customers/test2',
            },
        ],
        route: '/Marketing',
        hasChildren: true,
        icon: CircleOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
    },
    {
        id: '6',
        title: 'Delivery Options',
        children: [],
        hasChildren: false,
        icon: LocalShippingOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/deliveryOptions',
    },
    {
        id: '7',
        title: 'Payment Options',
        children: [],
        hasChildren: false,
        icon: AttachMoneyOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/paymentOptions',
    },
    {
        id: '8',
        title: 'Store Design',
        children: [],
        hasChildren: false,
        icon: BrushOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/storeDesign',
    },
    {
        id: '9',
        title: 'Subscription',
        children: [],
        hasChildren: false,
        icon: CreditCardOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/subscription',
    },
    {
        id: '11',
        title: 'Integrations',
        children: [],
        hasChildren: false,
        icon: LanguageRoundedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: 'integrations',
    },
    {
        id: '12',
        title: 'Extensions',
        children: [],
        hasChildren: false,
        icon: AppsRoundedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/extensions',
    },
    {
        id: '13',
        title: 'Setting',
        children: [],
        hasChildren: false,
        icon: SettingsOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/seting',
    },
    {
        id: '14',
        title: 'Logout',
        children: [],
        hasChildren: false,
        icon: LogoutRoundedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        hasSeparator: true,
        route: '/customers/test1',
    },
    {
        id: '15',
        title: 'Customer Support',
        children: [],
        hasChildren: false,
        icon: HelpOutlineRoundedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/customers/test1',
    },
    {
        id: '16',
        title: 'Share Your Shop',
        children: [],
        hasChildren: false,
        icon: ShareRoundedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/customers/test1',
    },
    {
        id: '17',
        title: 'View Your Shop',
        children: [],
        hasChildren: false,
        icon: VisibilityOutlinedIcon,
        isExpanded: false,
        isSelected: false,
        badgeValue: 0,
        route: '/customers/test1',
    },
]

export const DRAWER_WIDTH = 300

export const DATA_TYPES = {
    STRING: 'string',
    NUMBER: 'number',
    OBJECT: 'object',
    UNDEFINED: 'undefined',
    NULL: 'null',
}
